//  Minimal weight primitive polynomials over Z/2Z
//  In addition the coefficients/bits (apart from the
//  constant and the leading term) are as close to
//  the low end as possible.
//
//  Generated by Joerg Arndt, 2003-January-30

#pragma once

#include <vector>

extern const std::vector<std::vector<int> > minweight_primpoly_coeffs;