#!/bin/bash

set -evu

cd /cryptomite
mkdir wheelhouse
mkdir audited

for pyX in $PY_VERS
do
    cd /cryptomite
    export PYEX=/opt/python/${pyX}/bin/python
    ${PYEX} -m pip install -U pip wheel scikit-build
    ${PYEX} setup.py bdist_wheel -d "tmpwheel_${pyX}"
    auditwheel repair "tmpwheel_${pyX}/cryptomite-"*".whl" -w "audited/"
done
